name: Run CATS-Blender-Plugin tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Blender 5.1 via snap
      run: |
        sudo snap install blender --channel 5.1/stable --classic

    - name: Install plugin for Blender 5.1
      run: |
        mkdir -p ${HOME}/.config/blender/5.1/scripts/addons
        ln -s ${PWD} ${HOME}/.config/blender/5.1/scripts/addons/cats

    - name: Run unit tests
      run: |
        python3 ./tests/run.py --blend=blender -c True || exit 1
